apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komunalka
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: komunalka.misseddeadlines.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: komunalka-service
            port:
              number: 80
